name: Serverless Prod Deployment
on:
  push:
    branches:
      - "main"
      - "master"
concurrency:
  # Cancel in-progress deploys to main branch
  group: ${{ github.ref }}
  cancel-in-progress: true
env:
  DAGSTER_CLOUD_URL: ${{ secrets.DAGSTER_CLOUD_URL }}
  DAGSTER_CLOUD_API_TOKEN: ${{ secrets.DAGSTER_CLOUD_API_TOKEN }}
  

jobs: 
  parse_tenant1:
    name: Deploy Tenant 1
    runs-on: ubuntu-latest
    outputs:
      build_info: ${{ steps.parse-workspace.outputs.build_info }}
    
    steps:
     - name: Parse Tenant 1
       id: parse-workspace
       uses: dagster-io/dagster-cloud-action/actions/utils/parse_workspace@v0.1
       with:
         dagster_cloud_file: tenant1/dagster_cloud_tenant1.yaml

  deploy_tenant1:
    name: Deploy Tenant 1
    runs-on: ubuntu-latest
    if: needs.parse_tenant1.outputs.build_info
    needs: parse_tenant1
    strategy:
      fail-fast: false
      matrix:
        location: ${{ fromJSON(needs.parse_tenant1.outputs.build_info) }}
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          ref: ${{ github.head_ref }}
      - name: Copy Shared Package for Tenant1
        run: | 
          cp -r ./shared-asset-package ./tenant1/shared-asset-package  
      - name: Build and deploy to Dagster Cloud serverless
        uses: dagster-io/dagster-cloud-action/actions/serverless_prod_deploy@v0.1.15
        with:
          dagster_cloud_api_token: ${{ secrets.DAGSTER_CLOUD_API_TOKEN }}
          location: ${{ toJson(matrix.location) }}
          # Uncomment to pass through Github Action secrets as a JSON string of key-value pairs
          # env_vars: ${{ toJson(secrets) }}
          organization_id: ${{ secrets.ORGANIZATION_ID }}
          checkout_repo: 'false'
          deployment: 'tenant1'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  parse_tenant2:
    name: Deploy Tenant 2
    runs-on: ubuntu-latest
    outputs:
      build_info: ${{ steps.parse-workspace.outputs.build_info }}
    
    steps:
     - name: Parse Tenant 2
       id: parse-workspace
       uses: dagster-io/dagster-cloud-action/actions/utils/parse_workspace@v0.1
       with:
        dagster_cloud_file: tenant2/dagster_cloud_tenant2.yaml

  deploy_tenant2:
    name: Deploy Tenant 2
    runs-on: ubuntu-latest
    if: needs.parse_tenant2.outputs.build_info
    needs: parse_tenant2
    strategy:
      fail-fast: false
      matrix:
        location: ${{ fromJSON(needs.parse_tenant2.outputs.build_info) }}
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          ref: ${{ github.head_ref }}
      - name: Copy Shared Package for Tenant 2
        run: | 
          cp -r ./shared-asset-package ./tenant2/shared-asset-package  
      - name: Build and deploy to Dagster Cloud serverless
        uses: dagster-io/dagster-cloud-action/actions/serverless_prod_deploy@v0.1.15
        with:
          dagster_cloud_api_token: ${{ secrets.DAGSTER_CLOUD_API_TOKEN }}
          location: ${{ toJson(matrix.location) }}
          # Uncomment to pass through Github Action secrets as a JSON string of key-value pairs
          # env_vars: ${{ toJson(secrets) }}
          organization_id: ${{ secrets.ORGANIZATION_ID }}
          checkout_repo: 'false'
          deployment: 'tenant2'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    


